# Generated by Django 5.0.1 on 2024-01-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=18, default=0, editable=False, max_digits=36),
        ),
    ]
